<?php
/**
 * Copyright © 2018 Cointopay. All rights reserved.
 * See COPYING.txt for license details.
 */

$order = $block->getCointopayOrder();
if($order){
	//echo $this->getBaseUrl();
if($block->getPrevpage() == $this->getBaseUrl().'checkout/'){ 
$payment_method_code = $order->getPayment()->getMethodInstance()->getCode();
if ($payment_method_code == 'cointopaycc_gateway') {
?>
<a class="action primary" style="float: left;" href="<?= $this->getBaseUrl() ?>paymentcointopaycc/ctpinfo/index/">Click here to check your cointopay cc invoice detail</a>
<?php }}}?>
